### PR TITLE
Absolutely minimal tests.

### PR DESCRIPTION
**Pull request by a1exsh**

### CODE REVIEW

**Comment by hjacobs** [comment]
Yeah, tests :tada: 

Can you check the conflict?

**Comment by a1exsh** [comment]
Yeah, unfortunately I couldn't make the test run w/o making a module.  Is there a way to avoid that and should we?

**Comment by hjacobs** [comment]
A module is good to have :smile:

**Comment by a1exsh** [comment]
Will have to reopen PR after rebase.

**Pull request closed without merging**
